[profile.default]
src = "src"
out = "out"
ffi = true
ast = true
build_info = true
libs = ["lib"]
test = "test"
fs_permissions = [{ access = "read-write", path = "./"}]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


dotenv = ".env"


[rpc_endpoints]
base_sepolia = "${RPC_URL}"


[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }

